[openwrt]
router01 ansible_host=192.168.99.1 ansible_user=root

[domain_controllers]
dc01 ansible_host=192.168.99.10
dc02 ansible_host=192.168.99.11

[windows]
dc01 ansible_host=192.168.99.10
dc02 ansible_host=192.168.99.11

[windows:vars]
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_user=Administrator
ansible_password="{{ vault_windows_admin_password }}"

[linux]
infra01 ansible_host=192.168.99.22 ansible_user=simo
wiki01 ansible_host=192.168.99.40 ansible_user=simo
docker01 ansible_host=192.168.99.50 ansible_user=simo

[docker_hosts]
docker01 ansible_host=192.168.99.50 ansible_user=simo

[ansible]
infra01 ansible_host=192.168.99.22 ansible_user=simo

[wikijs]
wiki01 ansible_host=192.168.99.40 ansible_user=simo
